// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxorepfgkdfxyojbigce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4b3JlcGZna2RmeHlvamJpZ2NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NDE5NjYsImV4cCI6MjA3MzQxNzk2Nn0.bBmau16Kr4qGEV2PwUefCKTdQUZMmLONqbGwlu9dFYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});